BEGIN
    FOR i IN (SELECT table_name FROM user_tables) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || i.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
    FOR i IN (SELECT sequence_name FROM user_sequences) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || i.sequence_name;
    END LOOP;
END;
/

CREATE SEQUENCE SEQ_ENDERECO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CLIENTE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FORNECEDOR START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CENTRO_DISTRIBUICAO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TRANSPORTADORA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATEGORIA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRODUTO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRODUTO_FOTO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CARRINHO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ORDEM_COMPRA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_NOTA_FISCAL START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EMAIL START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE ENDERECO (
    CODIGO NUMBER DEFAULT SEQ_ENDERECO.NEXTVAL NOT NULL,
    RUA VARCHAR2(150) NOT NULL,
    NUMERO VARCHAR2(20)NOT NULL,
    BAIRRO VARCHAR2(100) NOT NULL,
    CIDADE VARCHAR2(100) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CEP VARCHAR2(9) NOT NULL,
    CONSTRAINT PK_ENDERECO PRIMARY KEY (CODIGO)
);

CREATE TABLE CLIENTE (
    CODIGO NUMBER DEFAULT SEQ_CLIENTE.NEXTVAL NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    SOBRENOME VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    SEXO CHAR(1) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL,
    TELEFONE_OBRIGATORIO VARCHAR2(25) NOT NULL,
    PONTOS NUMBER DEFAULT 0 NOT NULL,
    CODIGO_ENDERECO NUMBER NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO),
    CONSTRAINT UK_CLIENTE_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_CLIENTE_ENDERECO FOREIGN KEY (CODIGO_ENDERECO) REFERENCES ENDERECO(CODIGO),
    CONSTRAINT CK_CLIENTE_SEXO CHECK (SEXO IN ('M', 'F', 'O')),
    CONSTRAINT CK_CLIENTE_PONTOS CHECK (PONTOS >= 0)
);

CREATE TABLE CLIENTE_TELEFONE (
    CODIGO_CLIENTE NUMBER NOT NULL,
    TELEFONE VARCHAR2(25) NOT NULL,
    CONSTRAINT PK_CLIENTE_TELEFONE PRIMARY KEY (CODIGO_CLIENTE, TELEFONE),
    CONSTRAINT FK_CT_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO) ON DELETE CASCADE
);

CREATE TABLE INDICACAO (
    CODIGO_INDICADOR NUMBER NOT NULL,
    CODIGO_INDICADO NUMBER NOT NULL,
    DATA_INDICACAO DATE NOT NULL,
    CONSTRAINT PK_INDICACAO PRIMARY KEY (CODIGO_INDICADOR, CODIGO_INDICADO),
    CONSTRAINT FK_INDICACAO_INDICADOR FOREIGN KEY (CODIGO_INDICADOR) REFERENCES CLIENTE(CODIGO),
    CONSTRAINT FK_INDICACAO_INDICADO FOREIGN KEY (CODIGO_INDICADO) REFERENCES CLIENTE(CODIGO),
    CONSTRAINT UK_INDICACAO_INDICADO UNIQUE (CODIGO_INDICADO)
);

CREATE TABLE FORNECEDOR (
    CODIGO NUMBER DEFAULT SEQ_FORNECEDOR.NEXTVAL NOT NULL,
    NOME VARCHAR2(150) NOT NULL,
    EMAIL_CONTATO VARCHAR2(150),
    TELEFONE VARCHAR2(25),
    HOME_PAGE VARCHAR2(200),
    CODIGO_ENDERECO NUMBER NOT NULL,
    CONSTRAINT PK_FORNECEDOR PRIMARY KEY (CODIGO),
    CONSTRAINT FK_FORNECEDOR_ENDERECO FOREIGN KEY (CODIGO_ENDERECO) REFERENCES ENDERECO(CODIGO)
);

CREATE TABLE CENTRO_DISTRIBUICAO (
    CODIGO NUMBER DEFAULT SEQ_CENTRO_DISTRIBUICAO.NEXTVAL NOT NULL,
    NOME VARCHAR2(150) NOT NULL,
    CODIGO_ENDERECO NUMBER NOT NULL,
    CONSTRAINT PK_CENTRO_DISTRIBUICAO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_CD_ENDERECO FOREIGN KEY (CODIGO_ENDERECO) REFERENCES ENDERECO(CODIGO)
);

CREATE TABLE TRANSPORTADORA (
    CODIGO NUMBER DEFAULT SEQ_TRANSPORTADORA.NEXTVAL NOT NULL,
    NOME VARCHAR2(150) NOT NULL,
    EMAIL VARCHAR2(150),
    TELEFONE VARCHAR2(25),
    SITE VARCHAR2(200),
    CODIGO_ENDERECO NUMBER NOT NULL,
    CONSTRAINT PK_TRANSPORTADORA PRIMARY KEY (CODIGO),
    CONSTRAINT FK_TRANSPORTADORA_ENDERECO FOREIGN KEY (CODIGO_ENDERECO) REFERENCES ENDERECO(CODIGO)
);

CREATE TABLE CATEGORIA (
    CODIGO NUMBER DEFAULT SEQ_CATEGORIA.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (CODIGO),
    CONSTRAINT UK_CATEGORIA_NOME UNIQUE (NOME)
);

CREATE TABLE PRODUTO (
    CODIGO NUMBER DEFAULT SEQ_PRODUTO.NEXTVAL NOT NULL,
    NOME VARCHAR2(200) NOT NULL,
    PRECO NUMBER(10, 2) NOT NULL,
    FOTO_OBRIGATORIA BLOB NOT NULL,
    DESCRICAO CLOB,
    ESPECIFICACAO CLOB,
    DATA_FABRICACAO DATE,
    DATA_VALIDADE DATE,
    CODIGO_CATEGORIA NUMBER NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES CATEGORIA(CODIGO),
    CONSTRAINT CK_PRODUTO_PRECO CHECK (PRECO >= 0)
);

CREATE TABLE PRODUTO_FOTO (
    CODIGO NUMBER DEFAULT SEQ_PRODUTO_FOTO.NEXTVAL NOT NULL,
    CODIGO_PRODUTO NUMBER NOT NULL,
    FOTO BLOB NOT NULL,
    CONSTRAINT PK_PRODUTO_FOTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PF_PRODUTO FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO(CODIGO) ON DELETE CASCADE
);

CREATE TABLE PRODUTO_FORNECEDOR (
    CODIGO_PRODUTO NUMBER NOT NULL,
    CODIGO_FORNECEDOR NUMBER NOT NULL,
    CONSTRAINT PK_PRODUTO_FORNECEDOR PRIMARY KEY (CODIGO_PRODUTO, CODIGO_FORNECEDOR),
    CONSTRAINT FK_PF_PRODUTO_ID FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO(CODIGO),
    CONSTRAINT FK_PF_FORNECEDOR_ID FOREIGN KEY (CODIGO_FORNECEDOR) REFERENCES FORNECEDOR(CODIGO)
);

CREATE TABLE ITEM_INVENTARIO (
    CODIGO_PRODUTO NUMBER NOT NULL,
    CODIGO_CENTRO_DISTRIBUICAO NUMBER NOT NULL,
    QUANTIDADE NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_ITEM_INVENTARIO PRIMARY KEY (CODIGO_PRODUTO, CODIGO_CENTRO_DISTRIBUICAO),
    CONSTRAINT FK_II_PRODUTO FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO(CODIGO),
    CONSTRAINT FK_II_CENTRO_DIST FOREIGN KEY (CODIGO_CENTRO_DISTRIBUICAO) REFERENCES CENTRO_DISTRIBUICAO(CODIGO),
    CONSTRAINT CK_ITEM_INVENTARIO_QTD CHECK (QUANTIDADE >= 0)
);

CREATE TABLE CUPOM_DESCONTO (
    CODIGO VARCHAR2(50) NOT NULL,
    PORCENTAGEM_DESCONTO NUMBER(5, 2) NOT NULL,
    CONSTRAINT PK_CUPOM_DESCONTO PRIMARY KEY (CODIGO),
    CONSTRAINT CK_CUPOM_DESCONTO_VALOR CHECK (PORCENTAGEM_DESCONTO > 0 AND PORCENTAGEM_DESCONTO <= 100)
);

CREATE TABLE CUPOM_CATEGORIA (
    CODIGO_CUPOM VARCHAR2(50) NOT NULL,
    CODIGO_CATEGORIA NUMBER NOT NULL,
    CONSTRAINT PK_CUPOM_CATEGORIA PRIMARY KEY (CODIGO_CUPOM, CODIGO_CATEGORIA),
    CONSTRAINT FK_CC_CUPOM FOREIGN KEY (CODIGO_CUPOM) REFERENCES CUPOM_DESCONTO(CODIGO) ON DELETE CASCADE,
    CONSTRAINT FK_CC_CATEGORIA FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES CATEGORIA(CODIGO) ON DELETE CASCADE
);

CREATE TABLE RESGATE_CUPOM (
    CODIGO_CLIENTE NUMBER NOT NULL,
    CODIGO_CUPOM VARCHAR2(50) NOT NULL,
    DATA_RESGATE DATE NOT NULL,
    CONSTRAINT PK_RESGATE_CUPOM PRIMARY KEY (CODIGO_CLIENTE, CODIGO_CUPOM, DATA_RESGATE),
    CONSTRAINT FK_RC_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO),
    CONSTRAINT FK_RC_CUPOM FOREIGN KEY (CODIGO_CUPOM) REFERENCES CUPOM_DESCONTO(CODIGO)
);

CREATE TABLE CARRINHO (
    CODIGO NUMBER DEFAULT SEQ_CARRINHO.NEXTVAL NOT NULL,
    CODIGO_CLIENTE NUMBER NOT NULL,
    CODIGO_CUPOM VARCHAR2(50),
    DATA_CRIACAO DATE NOT NULL,
    CONSTRAINT PK_CARRINHO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_CARRINHO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO),
    CONSTRAINT FK_CARRINHO_CUPOM FOREIGN KEY (CODIGO_CUPOM) REFERENCES CUPOM_DESCONTO(CODIGO),
    CONSTRAINT UK_CARRINHO_CLIENTE UNIQUE (CODIGO_CLIENTE)
);

CREATE TABLE ITEM_CARRINHO (
    CODIGO_CARRINHO NUMBER NOT NULL,
    CODIGO_PRODUTO NUMBER NOT NULL,
    QUANTIDADE NUMBER NOT NULL,
    CONSTRAINT PK_ITEM_CARRINHO PRIMARY KEY (CODIGO_CARRINHO, CODIGO_PRODUTO),
    CONSTRAINT FK_IC_CARRINHO FOREIGN KEY (CODIGO_CARRINHO) REFERENCES CARRINHO(CODIGO) ON DELETE CASCADE,
    CONSTRAINT FK_IC_PRODUTO FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO(CODIGO),
    CONSTRAINT CK_ITEM_CARRINHO_QTD CHECK (QUANTIDADE > 0)
);

CREATE TABLE ORDEM_COMPRA (
    CODIGO NUMBER DEFAULT SEQ_ORDEM_COMPRA.NEXTVAL NOT NULL,
    DATA_PEDIDO DATE NOT NULL,
    STATUS VARCHAR2(30) NOT NULL,
    DESCONTO_APLICADO NUMBER(10, 2) DEFAULT 0,
    PRECO_FRETE NUMBER(10, 2) DEFAULT 0,
    CODIGO_ENDERECO_ENTREGA NUMBER NOT NULL,
    CODIGO_CLIENTE NUMBER NOT NULL,
    CODIGO_TRANSPORTADORA NUMBER NOT NULL,
    CONSTRAINT PK_ORDEM_COMPRA PRIMARY KEY (CODIGO),
    CONSTRAINT FK_OC_ENDERECO FOREIGN KEY (CODIGO_ENDERECO_ENTREGA) REFERENCES ENDERECO(CODIGO),
    CONSTRAINT FK_OC_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO),
    CONSTRAINT FK_OC_TRANSPORTADORA FOREIGN KEY (CODIGO_TRANSPORTADORA) REFERENCES TRANSPORTADORA(CODIGO),
    CONSTRAINT CK_OC_STATUS CHECK (STATUS IN ('Aguardando Pagamento', 'Em separação', 'Em transporte', 'Finalizada')),
    CONSTRAINT CK_OC_DESCONTO CHECK (DESCONTO_APLICADO >= 0),
    CONSTRAINT CK_OC_FRETE CHECK (PRECO_FRETE >= 0)
);

CREATE TABLE ITEM_ORDEM_COMPRA (
    CODIGO_ORDEM_COMPRA NUMBER NOT NULL,
    CODIGO_PRODUTO NUMBER NOT NULL,
    QUANTIDADE NUMBER NOT NULL,
    VALOR_UNITARIO_ATUAL NUMBER(10, 2) NOT NULL,
    CONSTRAINT PK_ITEM_ORDEM_COMPRA PRIMARY KEY (CODIGO_ORDEM_COMPRA, CODIGO_PRODUTO),
    CONSTRAINT FK_IOC_ORDEM_COMPRA FOREIGN KEY (CODIGO_ORDEM_COMPRA) REFERENCES ORDEM_COMPRA(CODIGO),
    CONSTRAINT FK_IOC_PRODUTO FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO(CODIGO),
    CONSTRAINT CK_IOC_QTD CHECK (QUANTIDADE > 0),
    CONSTRAINT CK_IOC_VALOR CHECK (VALOR_UNITARIO_ATUAL >= 0)
);

CREATE TABLE AVALIACAO_PRODUTO (
    CODIGO_ORDEM_COMPRA NUMBER NOT NULL,
    CODIGO_PRODUTO NUMBER NOT NULL,
    NOTA NUMBER NOT NULL,
    DESCRICAO VARCHAR2(1000),
    DATA_AVALIACAO DATE NOT NULL,
    CONSTRAINT PK_AVALIACAO_PRODUTO PRIMARY KEY (CODIGO_ORDEM_COMPRA, CODIGO_PRODUTO),
    CONSTRAINT FK_AP_ITEM_ORDEM FOREIGN KEY (CODIGO_ORDEM_COMPRA, CODIGO_PRODUTO) REFERENCES ITEM_ORDEM_COMPRA(CODIGO_ORDEM_COMPRA, CODIGO_PRODUTO),
    CONSTRAINT CK_AP_NOTA CHECK (NOTA BETWEEN 0 AND 5)
);

CREATE TABLE NOTA_FISCAL (
    CODIGO NUMBER DEFAULT SEQ_NOTA_FISCAL.NEXTVAL NOT NULL,
    NUMERO VARCHAR2(50) NOT NULL,
    SERIE VARCHAR2(10) NOT NULL,
    INSCRICAO_ESTADUAL VARCHAR2(30),
    CHAVE_ACESSO VARCHAR2(44) NOT NULL,
    VALOR_TOTAL NUMBER(12, 2) NOT NULL,
    CODIGO_ORDEM_COMPRA NUMBER NOT NULL,
    DATA_EMISSAO DATE NOT NULL,
    CONSTRAINT PK_NOTA_FISCAL PRIMARY KEY (CODIGO),
    CONSTRAINT UK_NF_ORDEM_COMPRA UNIQUE (CODIGO_ORDEM_COMPRA),
    CONSTRAINT FK_NF_ORDEM_COMPRA FOREIGN KEY (CODIGO_ORDEM_COMPRA) REFERENCES ORDEM_COMPRA(CODIGO),
    CONSTRAINT UK_NF_CHAVE_ACESSO UNIQUE (CHAVE_ACESSO),
    CONSTRAINT CK_NF_VALOR_TOTAL CHECK (VALOR_TOTAL >= 0)
);

CREATE TABLE EMAIL (
    CODIGO NUMBER DEFAULT SEQ_EMAIL.NEXTVAL NOT NULL,
    ASSUNTO VARCHAR2(200) NOT NULL,
    DATA_ENVIO DATE NOT NULL,
    CONTEUDO CLOB,
    CONSTRAINT PK_EMAIL PRIMARY KEY (CODIGO)
);

CREATE TABLE HISTORICO_EMAIL_CLIENTE (
    CODIGO_EMAIL NUMBER NOT NULL,
    CODIGO_CLIENTE NUMBER NOT NULL,
    ABRIU CHAR(1) DEFAULT 'N' NOT NULL,
    CLICOU_NO_CONTEUDO CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_HISTORICO_EMAIL_CLIENTE PRIMARY KEY (CODIGO_EMAIL, CODIGO_CLIENTE),
    CONSTRAINT FK_HEC_EMAIL FOREIGN KEY (CODIGO_EMAIL) REFERENCES EMAIL(CODIGO),
    CONSTRAINT FK_HEC_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO),
    CONSTRAINT CK_HEC_ABRIU CHECK (ABRIU IN ('S', 'N')),
    CONSTRAINT CK_HEC_CLICOU CHECK (CLICOU_NO_CONTEUDO IN ('S', 'N'))
);

CREATE TABLE HISTORICO_PRODUTO_VISUALIZADO (
    CODIGO_CLIENTE NUMBER NOT NULL,
    CODIGO_PRODUTO NUMBER NOT NULL,
    DATA_VISUALIZACAO TIMESTAMP NOT NULL,
    TEMPO_PERMANENCIA NUMBER,
    CONSTRAINT PK_HIST_PROD_VISUALIZADO PRIMARY KEY (CODIGO_CLIENTE, CODIGO_PRODUTO, DATA_VISUALIZACAO),
    CONSTRAINT FK_HPV_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO),
    CONSTRAINT FK_HPV_PRODUTO FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO(CODIGO),
    CONSTRAINT CK_HPV_TEMPO CHECK (TEMPO_PERMANENCIA >= 0)
);

CREATE TABLE HISTORICO_PRODUTO_CARRINHO (
    CODIGO_CLIENTE NUMBER NOT NULL,
    CODIGO_PRODUTO NUMBER NOT NULL,
    DATA_ADICAO DATE NOT NULL,
    FINALIZOU_COMPRA CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_HIST_PROD_CARRINHO PRIMARY KEY (CODIGO_CLIENTE, CODIGO_PRODUTO, DATA_ADICAO),
    CONSTRAINT FK_HPC_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO),
    CONSTRAINT FK_HPC_PRODUTO FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO(CODIGO),
    CONSTRAINT CK_HPC_FINALIZOU CHECK (FINALIZOU_COMPRA IN ('S', 'N'))
);
